name: Release Obsidian Plugin
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version or major, minor, patch'
        default: 'patch'
        required: true
      update-manifest:
        description: 'Update manifest.json'
        default: "true"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.7'

    # Build the plugin
    - name: Build and Tag
      id: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${{ github.event.inputs.version }}"
        echo "${{ github.event.inputs.update-manifest }}"
        git config user.name github-actions
        git config user.email github-actions@github.com

        npm install
        npm version ${{ github.event.inputs.version }} --no-git-tag-version
        VERSION=$(grep '^  "version"' package.json | cut -d'"' -f4)
        echo $VERSION

        if [ "${{ github.event.inputs.update-manifest }}" = "true" ]; then
          sed -i 's|\(version":\) "[0-9\.]*"|\1 "'$VERSION'"|' manifest.json
        fi

        git add .
        git status
        git commit -m "🔖 $VERSION"
        git push

        git tag $VERSION
        git push --tags

        npm run brat-notes -- ${VERSION}
        echo "::set-output name=version::${VERSION}"

    # Package the required files into a zip
    - name: Package
      run: |
        mkdir ${{ github.event.repository.name }}
        cp ./build/* ${{ github.event.repository.name }}
        zip -r ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}
    # Create the release on github
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ steps.build.outputs.version }}
      with:
        tag_name: ${{ steps.build.outputs.version }}
        release_name: Release ${{ steps.build.outputs.version }}
        body_path: ./release-notes.md
        draft: false
        prerelease: false
    # Upload the packaged release file
    - name: Upload zip file
      id: upload-zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ github.event.repository.name }}.zip
        asset_name: ${{ github.event.repository.name }}-${{ steps.build.outputs.version }}.zip
        asset_content_type: application/zip
    # Upload the main.js
    - name: Upload main.js
      id: upload-main
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/main.js
        asset_name: main.js
        asset_content_type: text/javascript
    # Upload the styles.css
    - name: Upload styles.css
      id: upload-css
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/styles.css
        asset_name: styles.css
        asset_content_type: text/css
    # Upload the manifest.json
    - name: Upload manifest.json
      id: upload-manifest
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./manifest.json
        asset_name: manifest.json
        asset_content_type: application/json
  brat:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - env:
        VERSION: ${{needs.build.outputs.version}}
      run: |
        echo $VERSION
        mversion=$(grep 'version' manifest-beta.json | cut -d'"' -f4)
        if [ "$VERSION" != "$mversion" ]; then
          sed -i 's|\(version":\) "[0-9\.]*"|\1 "'$VERSION'"|' manifest-beta.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "🔨 brat release $VERSION"
          git push
        fi
